// Pocket Racers service worker: makes the installed game work offline.
// Every game file is cached on install (the list is generated); after that
// the game loads from the cache, and a new version downloads in the
// background and takes over the next time the game starts.

// @generated by tools/precache.mjs — do not edit by hand
const VERSION = '7e92e8615410';
const PRECACHE = [
  './',
  'assets/audio/engine/manifest.json',
  'icons/icon-180.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-512.png',
  'icons/icon.svg',
  'manifest.webmanifest',
  'src/audio/audio.js',
  'src/audio/engine.js',
  'src/core/achievements.js',
  'src/core/autoQuality.js',
  'src/core/career.js',
  'src/core/garage.js',
  'src/core/loop.js',
  'src/core/profiles.js',
  'src/core/progress.js',
  'src/core/settings.js',
  'src/core/util.js',
  'src/data/achievements.js',
  'src/data/animals.js',
  'src/data/cars.js',
  'src/data/events.js',
  'src/data/kits.js',
  'src/data/props.js',
  'src/data/tracks/desertCanyon.js',
  'src/data/tracks/index.js',
  'src/data/tracks/nightCity.js',
  'src/data/tracks/snowyPeaks.js',
  'src/data/tracks/testTrack.js',
  'src/data/tracks/tropicalCoast.js',
  'src/data/vehicleFamilies.js',
  'src/data/vehicles.js',
  'src/gl/gl.js',
  'src/gl/math.js',
  'src/gl/meshBuilder.js',
  'src/input/inputManager.js',
  'src/input/tilt.js',
  'src/input/touchControls.js',
  'src/main.js',
  'src/render3d/animals.js',
  'src/render3d/carModel.js',
  'src/render3d/environment.js',
  'src/render3d/models.js',
  'src/render3d/particles.js',
  'src/render3d/props.js',
  'src/render3d/renderer3d.js',
  'src/render3d/terrain.js',
  'src/render3d/trackMesh.js',
  'src/sim/ai.js',
  'src/sim/fun.js',
  'src/sim/race.js',
  'src/sim/session.js',
  'src/ui/badgesScreen.js',
  'src/ui/garageScreen.js',
  'src/ui/homeScreens.js',
  'src/ui/hud.js',
  'src/ui/raceScreens.js',
  'src/ui/tuning.js',
  'src/world/track3d.js',
  'styles/main.css'
];
// @end
const CACHE = `pocketracers-${VERSION}`;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE.map((url) => new Request(url, { cache: 'reload' }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('pocketracers-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;
  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      // Pages are always the game shell; the query string never matters.
      const hit = await cache.match(req.mode === 'navigate' ? './' : req, { ignoreSearch: true });
      if (hit) return hit;
      const res = await fetch(req);
      // Files added later (e.g. sound packs) are kept for offline use too.
      if (res.ok && res.type === 'basic') cache.put(req, res.clone());
      return res;
    }),
  );
});
