// Offline support: lists every file the game needs and stamps the list and a
// content hash into sw.js. Run `npm run sw` after changing any shipped file;
// a unit test fails if sw.js is out of date. No dependencies.
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SHIPPED_DIRS = ['src', 'styles', 'icons', 'assets'];
const SHIPPED_FILES = ['index.html', 'manifest.webmanifest'];
const SKIP = /(^|\/)(README\.md|\.DS_Store)$/;

async function walk(dir) {
  const out = [];
  for (const e of await readdir(path.join(root, dir), { withFileTypes: true })) {
    const rel = `${dir}/${e.name}`;
    if (e.isDirectory()) out.push(...(await walk(rel)));
    else if (!SKIP.test(rel)) out.push(rel);
  }
  return out;
}

/** {files, version, source}: the expected sw.js for the current tree. */
export async function buildServiceWorker() {
  const files = [...SHIPPED_FILES];
  for (const d of SHIPPED_DIRS) files.push(...(await walk(d)));
  files.sort();
  const hash = createHash('sha256');
  for (const f of files) hash.update(f).update(await readFile(path.join(root, f)));
  const template = await readFile(path.join(root, 'sw.js'), 'utf8');
  const version = hash.update(template.replace(/\/\/ @generated[\s\S]*?\/\/ @end\n/, '')).digest('hex').slice(0, 12);
  const urls = ['./', ...files.filter((f) => f !== 'index.html')];
  const block = `// @generated by tools/precache.mjs — do not edit by hand\nconst VERSION = '${version}';\nconst PRECACHE = ${JSON.stringify(urls, null, 2).replace(/"/g, "'")};\n// @end\n`;
  const source = template.replace(/\/\/ @generated[\s\S]*?\/\/ @end\n/, block);
  return { files: urls, version, source, current: template };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const sw = await buildServiceWorker();
  if (sw.source === sw.current) console.log(`sw.js up to date (${sw.version}, ${sw.files.length} files)`);
  else {
    await writeFile(path.join(root, 'sw.js'), sw.source);
    console.log(`sw.js stamped ${sw.version} with ${sw.files.length} files`);
  }
}
